// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TfXE0xenj8WozyFYXO6JL-nlHTwOYHE',
    appId: '1:691655228359:web:8125e8feb6f5b994fb77e2',
    messagingSenderId: '691655228359',
    projectId: 'projeto-exemplo-aedd6',
    authDomain: 'projeto-exemplo-aedd6.firebaseapp.com',
    storageBucket: 'projeto-exemplo-aedd6.firebasestorage.app',
    measurementId: 'G-13CQP5E7EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtkJfwdcRoNYFTSjnFKTcyY54Trlu_F-Y',
    appId: '1:691655228359:android:de2e3d4347b44d84fb77e2',
    messagingSenderId: '691655228359',
    projectId: 'projeto-exemplo-aedd6',
    storageBucket: 'projeto-exemplo-aedd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp2ybI2hVudXFywZzdvRbnU-Fb9fG6o1M',
    appId: '1:691655228359:ios:8ed5e0f570ad489cfb77e2',
    messagingSenderId: '691655228359',
    projectId: 'projeto-exemplo-aedd6',
    storageBucket: 'projeto-exemplo-aedd6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp2ybI2hVudXFywZzdvRbnU-Fb9fG6o1M',
    appId: '1:691655228359:ios:8ed5e0f570ad489cfb77e2',
    messagingSenderId: '691655228359',
    projectId: 'projeto-exemplo-aedd6',
    storageBucket: 'projeto-exemplo-aedd6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9TfXE0xenj8WozyFYXO6JL-nlHTwOYHE',
    appId: '1:691655228359:web:1d92c77fc0a5264efb77e2',
    messagingSenderId: '691655228359',
    projectId: 'projeto-exemplo-aedd6',
    authDomain: 'projeto-exemplo-aedd6.firebaseapp.com',
    storageBucket: 'projeto-exemplo-aedd6.firebasestorage.app',
    measurementId: 'G-V2XRNH1D9X',
  );
}
